# Generated by Django 5.2 on 2025-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordineprodotto',
            old_name='quantità',
            new_name='quantita',
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='categoria',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
